CREATE OR REPLACE TABLE CHARTS_AGE_SEX_DISTRIBUTION AS 

SELECT DISTINCT PRACTICE_ID,
                AREA_ID,
                SEX,
                TEN_AGE_CAT,
                100.0 * COUNT(*) / SUM(COUNT(*)) OVER(PARTITION BY PRACTICE_ID) AS PATIENTS_PERCENT,
                100.0 * SUM(ENCOUNTERS_IN_STUDYPERIOD) / SUM(SUM(ENCOUNTERS_IN_STUDYPERIOD)) OVER(PARTITION BY PRACTICE_ID) AS ENCOUNTERS_PERCENT
FROM GPEHR_PATIENT_SUMMARY
GROUP BY PRACTICE_ID,
         AREA_ID,
         SEX,
         TEN_AGE_CAT
ORDER BY PRACTICE_ID,
         AREA_ID,
         SEX,
         TEN_AGE_CAT;
                
