CREATE OR REPLACE TABLE CHARTS_AGE_SEX_DISTRIBUTION_NSW AS 

SELECT DISTINCT SEX,
                TEN_AGE_CAT,
                100.0 * COUNT(*) / SUM(COUNT(*)) OVER() AS PATIENTS_PERCENT,
                100.0 * SUM(ENCOUNTERS_IN_STUDYPERIOD) / SUM(SUM(ENCOUNTERS_IN_STUDYPERIOD)) OVER() AS ENCOUNTERS_PERCENT
FROM GPEHR_PATIENT_SUMMARY
GROUP BY SEX,
         TEN_AGE_CAT
ORDER BY SEX,
         TEN_AGE_CAT;
                
