CREATE OR REPLACE TABLE CHARTS_AGE_SEX_DISTRIBUTION_PHN AS 

SELECT DISTINCT AREA_ID,
                SEX,
                TEN_AGE_CAT,
                100.0 * COUNT(*) / SUM(COUNT(*)) OVER(PARTITION BY AREA_ID) AS PATIENTS_PERCENT,
                100.0 * SUM(ENCOUNTERS_IN_STUDYPERIOD) / SUM(SUM(ENCOUNTERS_IN_STUDYPERIOD)) OVER(PARTITION BY AREA_ID) AS ENCOUNTERS_PERCENT
FROM GPEHR_PATIENT_SUMMARY
GROUP BY AREA_ID,
         SEX,
         TEN_AGE_CAT
ORDER BY AREA_ID,
         SEX,
         TEN_AGE_CAT;
                
