CREATE OR REPLACE TABLE GPEHR_PATIENT_SUMMARY AS

SELECT COHORT.*,
REF.AGECAT_TEXT AS TEN_AGE_CAT
FROM GPEHR_PATIENT_SUMMARY AS COHORT
LEFT JOIN REFERENCE_TENCAT_AGES AS REF
ON REF.AGE_LOW <= COHORT.AGE
AND COHORT.AGE < REF.AGE_HIGH;